trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'Pipeline-Dev_RegConn'
    repository: 'pipeline_dev_predictor'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: AzureCLI@2
  displayName: Deploy
  inputs:
    azureSubscription: 'Pipeline-Dev_ResourceConn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az containerapp update --name uae-modrek-pipeline-dev --resource-group uae-modrek-rg --container-name pipeline-predictor --image modrekregistry.azurecr.io/pipeline_dev_predictor:latest'