trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'Pipeline-Dev_RegConn'
    repository: 'pipeline_dev_predictor'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
- task: AzureContainerApps@1
  displayName: Deploy
  inputs:
    azureSubscription: 'Pipeline-Dev_ResourceConn'
    containerAppName: 'uae-modrek-pipeline-dev/pipeline-predictor'
    resourceGroup: 'uae-modrek-rg'
    imageToDeploy: 'modrekregistry.azurecr.io/pipeline_dev_predictor:latest'
