name: Branch Name Policy

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH="${{ github.head_ref }}"

          echo "Checking branch: $BRANCH"

          if [[ "$BRANCH" != "dev" ]]; then
            echo "::error::Incoming branch is not Dev."
            exit 1
          fi
