name: Qodana Security Scan
on:
  pull_request:
    branches:
      - master
      


jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: false
          args: --fail-threshold,0
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1505967784 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
      
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          category: qodana
